name: Caddy

on:
  workflow_dispatch:
  # schedule:
  #   - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest Caddy version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_tag=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r '.tag_name')

          echo "VERSION=${latest_tag#v}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tags
        run: |
          echo "TAGS=${{ secrets.DOCKERHUB_USERNAME }}/caddy-proxy:latest,${{ secrets.DOCKERHUB_USERNAME }}/caddy-proxy:${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.caddy
          push: true
          tags: ${{ env.TAGS }}
          build-args: |
            CADDY_VERSION=${{ env.VERSION }}
